== Selección de la Vida de Thomas Ellwood

Aunque es posible que mi condición--al no ser tan
eminente ni en la iglesia de Cristo ni en el mundo,
como otros que se han movido en niveles superiores--no
ofrezca cosas tan notables como las de ellos;
aun así,
puesto que en el curso de mis viajes por este valle
de lágrimas he pasado por varios ejercicios,
algunos poco comunes,
en los cuales le plació al Señor bondadosamente ayudarme y conducirme a través de ellos,
me parece por lo menos que es excusable, si no encomiable,
darle al mundo un pequeño relato de mi vida.
Al relatar las muchas liberaciones y preservaciones
que el Señor en Su gracia ha realizado por mí,
es mi deseo por un lado,
rendirle un agradecido reconocimiento y acción de
gracias por Su abundante bondad para conmigo.
Y por el otro,
si hay alguien recorriendo el mismo camino y pasando por el mismo o similares ejercicios,
espero que sea alentado a perseverar en el camino
de santidad y a confiar en el Señor con plena certidumbre,
independientemente de cuales sean las pruebas que le sobrevengan.

Empezaré, por tanto, con mis orígenes.
Nací en el año de nuestro Señor de 1639, a comienzos del mes octavo,
hasta donde he podido informarme; porque el registro parroquial que indica el día,
no del nacimiento, sino más bien del bautismo (como ellos lo llaman) no es confiable.

El lugar de mi nacimiento fue un pueblito campesino llamado Crowell,
situado en la parte alta de Oxfordshire, tres millas al este de Thame,
el pueblo comercial más cercano.
El nombre de mi padre era Walter Ellwood,
y el nombre de soltera de mi madre era Elizabeth Potman; ambos de buenas descendencias,
pero de familias en declive.
Lo que mi padre poseía,
que era una gran cantidad de tierras y más en dinero (como he escuchado),
lo había recibido de su abuelo Walter Gray, como también su nombre Walter,
cuya única hija era su madre.

En mi infancia, cuando apenas tenía unos dos años, me llevaron a Londres.
Porque como la guerra civil entre el rey y el parlamento estaba estallando en ese momento,
mi padre, que apoyaba al parlamento (aunque no tomó las armas),
creyendo que no estaba a salvo en el condado donde vivía,
que estaba muy cerca de los cuarteles del rey, se fue a Londres,
la ciudad que en aquel entonces respaldaba al parlamento.

Fui criado allí, aunque no sin mucha dificultad,
porque el aire de la ciudad no era apropiado para mi tierna contextura.
Y allí continué hasta que Oxford fue sometido y la guerra aparentemente había terminado.

Durante ese tiempo,
mis padres entablaron una amistad muy cercana con
la señora Springett (viuda de Sir William Springett,
quien murió sirviendo al parlamento) y quien después fue la esposa de Isaac Penington,
el hijo mayor del concejal Penington de Londres.
Como esa amistad pasó de los padres a los hijos,
muy pronto me convertí en el compañero de juegos de su hija Gulielma,
y me permitían montarme con ella en su pequeño coche,
que era llevado por su siervo por los alrededores de Lincoln`'s-Inn-Fields.
Menciono esto aquí,
porque la continuación de esa amistad fue el medio por el
que más adelante fui llevado a conocer la bendita Verdad,
y en las siguientes páginas tendré frecuentes razones de mencionar con honra esta familia,
con la que estoy bajo muchas y muy grandes deudas.

Poco después de la rendición de Oxford, mi padre regresó a su propiedad en Crowell;
que para ese momento tenía bastante necesidad de atender, ya que, según supongo,
había gastado la mayoría del dinero que le había dejado su abuelo para
mantenerse a sí mismo y a su familia a un costo elevado en Londres.
Mientras vivíamos en Londres,
mi hermano mayor--porque yo tenía un hermano y dos hermanas
mayores que yo--fue inscrito en una escuela privada,
en la casa de un tal Francis Atkinson, en un lugar llamado Hadley, cerca de Barnet,
en Hertfordshire,
donde hizo un buen progreso en el aprendizaje de los idiomas Latín y Francés.
Pero después de que dejamos la ciudad y nos volvimos a establecer en el campo,
lo sacaron de esa escuela privada y lo inscribieron en la escuela pública de Thame,
en Oxfordshire.
Yo también fui enviado allí, tan pronto como mi tierna edad lo permitió;
porque yo era en verdad muy joven cuando fui,
y parecía aún más joven de lo que era debido a mi pequeña estatura.
Por algunos años se consideró la posibilidad de que yo fuera un enano;
pero después de que llegué a los quince años más o menos, comencé a estirarme,
y no dejé de crecer hasta que alcancé el tamaño y la estatura promedio de los hombres.

En esa escuela, que en aquel entonces tenía buena reputación, progresé rápidamente,
ya que en ese tiempo tenía una facilidad natural para aprender;
de modo que después de la primera lectura de mi lección,
normalmente sentía que la había dominado.
Y sin embargo, pocos niños en la escuela desgastaron la vara del profesor más que yo,
lo cual era algo extraño. Porque aunque nunca fui azotado, que yo recuerde,
por no haber terminado mi lección, o por no exponerla bien, aun así,
al ser un poco entrometido, lleno de energía, con una mente inquieta y de manos activas,
no podía conformarme fácilmente a las reglas serias y sobrias de la escuela,
que en ese entonces pensaba que eran severas.
A menudo les hacía una que otra broma jocosa a mis compañeros,
lo que hacía que fuera corregido,
de modo que llegué a estar bajo la disciplina de la vara hasta dos veces en una mañana,
aunque nunca me quebré un hueso.

Si hubiera permanecido en esa escuela,
y a su debido tiempo continuado a una más avanzada,
probablemente habría llegado a ser un letrado;
porque se decía que tenía una capacidad genial para aprender.
Pero tan pronto como el gobierno republicano empezó a establecerse,
mi padre aceptó el cargo de juez de paz, lo cual no fue beneficioso en ninguna manera.
Ese nuevo cargo era solo por honor y costoso en todos los sentidos,
y lo llevó a vivir de una manera que se amoldara a eso.
Y como él había sacado a mi hermano de la escuela de Thame
y lo había inscrito en el colegio de Merton en Oxford,
donde lo colocó en la posición más elevada y costosa,
halló necesario reducir sus gastos en otra parte;
el golpe de lo cual cayó sobre mí. Porque él me sacó de
la escuela para ahorrarse el gasto de mantenerme allí;
lo que fue algo así como arrancar un fruto verde del árbol y echarlo
a un lado antes de que hubiera llegado a su debida madurez,
y luego se encogería y marchitaría,
y perdería ese poquito de jugo y sabor que había empezado a tener.

Así sucedió conmigo.
Porque al ser llevado a casa cuando era tan solo un joven,
y antes de haberme afirmado bien en mis estudios--aunque había
hecho un buen progreso en el Latín y había comenzado a aprender
Griego--y al ser dejado a mi libertad para hacer lo que quisiera,
muy pronto le dije adiós a mis libros, dejándolos por completo de lado,
y me volví adicto a esos entretenimientos y placeres juveniles
que el lugar me ofrecía y que mis recursos podían alcanzar.

De esa forma muy pronto comencé a perder el poco
conocimiento que había adquirido en la escuela;
y por dejar de usar mis libros de manera continua,
finalmente me volví tan ajeno al estudio, que no podía leer, y mucho menos entender,
una oración en Latín. De hecho, estaba tan consciente de eso,
que me esmeraba por evitar leer para otros, incluso un libro en inglés,
no fuera a ser que me topara con una palabra en Latín
y me pusiera en vergüenza al pronunciarla mal.

Así continué,
divirtiéndome en esas vanidades que eran consideradas recreaciones inofensivas;
entreteniendo a mis compañeros y familiares con discursos placenteros en nuestras conversaciones.
Hacía eso por la mera fuerza del ingenio y de las habilidades naturales,
sin la ayuda de la educación escolar; y también era considerado buena compañía.

Sin embargo, siempre me rodeaba de personas honestas, moderadas y sobrias,
porque aborrecía la obscenidad en las conversaciones
y sentía una aversión natural a beber en exceso.
De modo que, en el tiempo de mi más grande vanidad,
el Señor me preservó de blasfemar y de cometer los peores males del mundo;
lo que me hizo agradable a las personas más estimadas de ese condado.
A menudo visitaba al señor Thomas Wenman^
footnote:[Señor Thomas Wenman,
era un terrateniente y político inglés que se sentó
en la Casa de Comunes varias veces entre 1621 y 1660.]
en su casa en Thame-park, como a dos millas de Crowell, donde yo vivía;
a cuyo favor tenía derecho por dos razones:
porque mi madre era pariente cercana de su esposa,
y porque a él le había placido otorgarme su nombre
al hacer grandes promesas para mí en mi bautismo.
Era una persona de gran honor y virtud, y siempre me recibió amablemente en su mesa,
sin importar cuán a menudo fuera.
Y tengo razones para creer que habría recibido del señor
Thomas algunos privilegios ventajosos en este mundo,
tan pronto como él me hubiera considerado capaz de recibirlos,
si no hubiera sido llamado (poco tiempo después de
eso) al servicio del mejor y más grande Señor;
y así perdí el favor de todos mis amigos, parientes y conocidos en este mundo.
Me apresuro a contar ese cambio tan feliz,
y por eso omitiré intencionalmente muchas particularidades de mi juventud.
Sin embargo, quiero mencionar un acontecimiento,
debido al efecto que tuvo sobre mí más adelante, que fue el siguiente:

Mi padre, que en ese entonces estaba comisionado como juez de paz,
iba a una sesión de la corte en Watlington y yo lo acompañaba.
Cuando estábamos cerca del pueblo,
el cochero vio un camino más corto y fácil que la ruta común,
que atravesaba un campo de maíz,
y al notar que era suficientemente ancho como para
que las ruedas del coche pasaran sin dañar el maíz,
tomó ese camino.
Cuando un labrador que estaba arando no muy lejos lo vio, corrió hacia nosotros,
y deteniendo el coche soltó un montón de quejas en un lenguaje bastante desagradable,
por haber conducido sobre el maíz. Mi padre le respondió suavemente diciendo,
que si se había cometido alguna ofensa,
él debía imputársela a su siervo más que a él mismo;
ya que él no le había ordenado conducir por ese camino,
ni sabía por cuál camino conducía. Sin embargo añadió,
que iba de camino a cierta posada en el pueblo, y que si el hombre lo encontraba allí,
le compensaría plenamente por cualquier daño que hubiera sufrido.
Y entonces seguimos adelante,
mientras que el hombre continuaba ventilando su descontento en un tono airado.
En el pueblo, después de preguntar,
nos enteramos de que efectivamente era un camino usado por los viajeros con frecuencia,
sin causar ningún daño, ya que era suficientemente ancho; pero que no era la ruta común,
la cual, sin embargo, no estaba muy lejos, y que también era suficientemente buena.
Por lo tanto, mi padre le ordenó a su siervo conducir a casa por la ruta común.

Regresamos tarde por la noche y estaba muy oscuro; y aquel hombre pendenciero,
que en la mañana nos había causado problemas a nosotros y a sí mismo,
consiguió la ayuda de otro sujeto tan robusto como él y nos esperaron en la oscuridad,
pensando que regresaríamos por el mismo camino que habíamos tomado.
Pero cuando se dieron cuenta de que no lo hacíamos, sino que íbamos por el camino común,
molestos por la frustración, y no queriendo abandonar su propósito de maltratarnos,
se apresuraron a caer sobre nosotros en la oscuridad,
y agarrando los frenos de nuestros caballos los detuvieron.
Mi padre le preguntó a su siervo la razón por la que no seguía adelante,
y él le respondió que había dos hombres a la cabeza de los caballos que estaban deteniéndolos,
y no los dejaban avanzar.
Entonces mi padre abrió el coche y salió, y yo lo seguí muy de cerca.
Yendo a donde estaban los hombres, les demandó la razón de ese asalto.
Ellos dijeron que estábamos conduciendo sobre su maíz;
pero nosotros sabíamos que no estábamos sobre el maíz, sino en el camino común,
y así se los dijimos.
Pero ellos nos dijeron que habían decidido no dejarnos avanzar más,
sino que nos harían regresar.
Mi padre trató de persuadirlos con suaves razonamientos a que desistieran
y no se metieran más en peligro con la ley,
en el cual ya se habían metido bastante; pero lo único que hicieron fue burlarse.
Por tanto, al ver que los medios gentiles no funcionaban con ellos,
les habló más rudamente, demandándoles que entregaran sus garrotes,
porque cada uno tenía un gran garrote en su mano.
Riéndose, le dijeron que no los habían llevado hasta ahí con esa intención. Con lo cual,
mi padre volteó su cabeza hacia mí y dijo: "`Tom, desármalos.`"

Yo estaba listo a su lado, solo esperando la orden.
Porque siendo naturalmente de un espíritu valiente y lleno de pasión juvenil,
la cual estaba intensificada en ese momento por la consciencia que tenía,
no solo del abuso,
sino del comportamiento insolente de esos violentos sujetos--mi
sangre comenzó a hervir y me picaban las manos,
como dice el dicho, queriendo encargarme de ellos.
Por lo tanto,
di valientemente un paso adelante para tomar la vara del que estaba más cerca de mí,
y le dije: "`Sirrah, entrega tu arma.`"
En eso levantó su garrote, que era suficientemente grande como para derribar a un buey,
intentando, sin ninguna duda, derribarme con él, lo que probablemente habría hecho si yo,
en un abrir y cerrar de ojos,
no hubiera sacado mi espada y realizado un ataque contra
él. Le habría enterrado la espada hasta la empuñadura,
si él hubiera mantenido su posición;
pero cuando repentina e inesperadamente vio el resplandor
de mi espada que brillaba en la oscura noche,
se sorprendió y se aterró tanto, que deslizándose hacia a un lado, evitó mi estocada.
Entonces dejando caer su garrote al suelo, salió corriendo para protegerse, lo cual,
al verlo su compañero, huyó también. Seguí al primero tan rápido como pude,
pero el miedo le había dado alas y lo hizo huir rápidamente.
Y aunque me consideraban muy rápido, cuanto más corríamos más se alejaba de mí,
y no lo pude alcanzar;
lo que me hizo pensar que se había escondido en algún arbusto que él conocía, pero yo no.
Mientras tanto, el cochero se excusaba a sí mismo por no haberse metido,
con el pretexto de que no se atrevía a dejar sus caballos, y así me dejó a mi suerte.
Yo había corrido tan lejos, que no sabía cómo regresar,
hasta que gritando y recibiendo gritos como respuesta, fui dirigido hacia mi grupo.

Teníamos medios para averiguar fácilmente quiénes eran esos hombres,
porque el principal de ellos había estado en la posada
durante el día y había peleado con el cochero,
amenazando con vengarse de él cuando regresara.
Pero dado que no habían logrado nada con su asalto,
mi padre pensó que era mejor no saber quiénes eran,
que obligarse a realizar una acción judicial.

En ese momento, y por un buen tiempo después,
no tuve ningún remordimiento en mi mente por lo que había hecho,
o por lo que habría hecho en ese caso; sino que seguí adelante,
en una especie de valentía,
determinado a matar a cualquier hombre que intentara algo similar,
o que nos hiciera alguna afrenta.
Y por esa razón,
rara vez hacía alguna excursión como esa sin una pistola cargada en mi bolsillo.
Pero cuando le plació al Señor, en Su infinita bondad,
llamarme a salir del espíritu del mundo y de sus caminos,
y concederme el conocimiento de la Verdad que salva,
por la que las acciones de mi vida pasada fueron puestas en orden delante de mí--entonces,
una especie de horror cayó sobre mí,
cuando consideré cuán cerca había estado de manchar mis manos con sangre humana.
Y después, cada vez que he pasado por ese camino, y de hecho,
cada vez que ese suceso viene a mi memoria, mi alma bendice al Señor por haberme librado,
y se levantan acciones de gracias y alabanzas en mi corazón (como sucede ahora mientras
lo relato) para Aquel que me preservó e impidió que derramara sangre humana.
Esta es la razón por la que he escrito de este suceso,
para que sirva de advertencia a otros.

Por ese tiempo, en el año 1658, mi querida y honorable madre,
que era en verdad una mujer de extraordinaria dignidad y virtud, dejó esta vida,
habiendo oído un poco antes de la muerte de su hijo mayor.

Como ya mencioné, durante el tiempo en que mi padre vivió en Londres,
en la época de la guerra civil,
él entabló amistad con la señora Springett--quien en ese entonces era viuda,
y luego se casó con Isaac Penington--y para mantener esa relación,
a veces iba a visitarlos a su casa de campo cerca de Reading.
Cuando se enteró de que se habían mudado a su propiedad en Chalfont, Buckinghamshire,
como a quince millas de Crowell, fue un día a visitarlos y me llevó con él,
y regresamos a nuestro hogar por la noche.
Cuando llegamos ahí nos sorprendió mucho, primero oír y luego encontrar,
que se habían vuelto Cuáqueros--un pueblo del que no sabíamos nada,
y un nombre del que habíamos oído escasamente hasta ese momento.
Al encontrar un cambio tan grande, de su comportamiento libre,
elegante y sofisticado que anteriormente les habíamos visto,
a la estricta seriedad con la que nos recibieron en ese momento,
nos hizo sentir tanto divertidos como defraudados en nuestra expectativa
de tener una visita tan placentera como las que solíamos tener.
Y como había otros forasteros con ellos,
parientes de Isaac Penington que habían llegado esa mañana de Londres a visitarlos,
mi padre no tuvo la oportunidad, mediante una conversación privada con ellos,
de entender la razón o motivo de ese cambio.

Por mi parte, busqué y eventualmente encontré la manera de estar en compañía de su hija,
Gulielma,^
footnote:[Unos años después de esto, Guleilma se casó con William Penn]
a quién encontré recogiendo flores en el jardín con la ayuda de su criada,
que también era Cuáquera.
Pero cuando me dirigí a ella de la manera en que acostumbraba,
tratando de empezar una conversación basándome en nuestra antigua relación,
aunque me trató de forma cortés, la seriedad de su mirada y comportamiento,
a pesar de lo joven que era, me causaron un temor tan grande,
que no me vi con suficiente dominio de mí mismo como
para buscar más conversación con ella.
Por lo tanto,
pidiéndole disculpas por mi atrevimiento al haberme entrometido en sus paseos privados,
me retiré, pero no sin algo de confusión mental.

Nos quedamos para la cena,
la cual fue muy agradable y a mi parecer no le faltó
nada aparte de las risas y discursos placenteros,
que no pudimos tener ni con ellos ni entre nosotros mismos por causa de ellos.
Porque la seriedad que estaba sobre sus espíritus y semblantes
detenía la ligereza que se hubiera levantado en nosotros.

Sin embargo, nos quedamos hasta que el resto del grupo se despidió de ellos,
y luego nosotros también regresamos a casa, no muy contentos de nuestro viaje,
pero sin saber qué cosas en particular reprochar.
Sin embargo, esa visita tuvo un buen efecto sobre mi padre,
quien entonces era juez de paz,
porque lo preparó para tener una opinión y una conducta más favorables
hacia ese pueblo cuando aparecieran en su camino;
como le sucedió a uno de ellos no mucho después. Porque un joven que vivía en Buckinghamshire,
llegó un Primer-día a la iglesia (así llamada) de un pueblo llamado Chinner,
a una milla de Crowell, teniendo en su mente, al parecer,
la carga de decirle algo al ministro de esa parroquia.
Ese ministro, que era un conocido mío, a veces me invitaba a oírlo,
como sucedió ese día. El joven estuvo de pie en el
pasillo frente al púlpito durante todo el sermón,
y no dijo una palabra hasta que el sermón y la oración posterior habían terminado.
Entonces le habló unas pocas palabras al sacerdote,
de las cuales todo lo que pude oír fue,
que "`la oración del impío es abominación al Señor,`" y "`que Dios no oye a los pecadores.`"

Creo que dijo algo más que no pude oír claramente debido al ruido de la gente.
Y él probablemente hubiese dicho más,
si no hubiera sido interrumpido por los oficiales
que lo detuvieron y lo sacaron del edificio,
a fin de llevarlo ante mi padre.

Cuando entendí eso, me apresuré a ir a casa,
para poder darle a mi padre una descripción justa
del asunto antes de que llegaran los oficiales.
Le dije que el joven se había comportado de manera quieta y pasiva,
que no había dicho una palabra hasta que el ministro había terminado todo su servicio,
y que lo que había dicho luego había sido algo corto
y expresado sin pasión ni malas palabras.
Sabía que eso le daría a mi padre una razón justa para dejar libre al hombre,
si así lo quería. Y en consecuencia,
cuando los oficiales llegaron y presentaron su enorme
queja contra el hombre (que dijo muy poco en su defensa),
mi padre los interrogó acerca de las palabras que había dicho,
respecto a las cuales no concordaron bien.
Y cuando les preguntó acerca del momento en que las había dicho,
todos concordaron en que había sido después de que el ministro había terminado;
y en cuanto a si él le había hablado al ministro con un lenguaje injurioso,
o si había tratado de levantar un tumulto entre la gente,
admitieron que no podían acusarlo de nada de eso.
Por lo tanto, al no hallar que el joven hubiera quebrantado la ley,
mi padre le aconsejó que tuviera cuidado de no causar
más disturbios públicos--y entonces lo despidió;
lo cual me alegró.

Un tiempo después de eso, mi padre,
habiendo oído más acerca del pueblo llamado Cuáqueros,
y deseando recibir información sobre sus principios,
les hizo otra visita a Isaac Penington y a su esposa en su casa llamada Grange,
en Peter`'s Chalfont, y me llevó a mí y a mis hermanas con él.

Fuimos allá en el décimo mes del año 1659,
donde nos recibieron muy amablemente y nos quedamos algunos días. Mientras estábamos
ahí se fijó una reunión en un lugar que estaba como a una milla de la casa,
a la cual fuimos invitados y fuimos gustosos.
Se llevó a cabo en una casa de campo llamada The Grove,
que antes había sido la residencia de un noble y tenía un salón muy grande,
el cual las personas llenaron completamente.

A esa reunión asistió Edward Burrough, junto con otros predicadores,
como Thomas Curtis y James Nayler;
pero ninguno habló en ese momento salvo Edward Burrough.
Me tocó estar sentado en un taburete junto a él,
al lado de una mesa larga en la que él se había sentado,
y bebí sus palabras con gran anhelo; porque ellas no solo alcanzaron mi entendimiento,
sino que también calentaron mi corazón con un cierto fuego,
que hasta ese día nunca había sentido a través del ministerio de ningún hombre.

Cuando la reunión terminó, nuestros amigos nos llevaron a casa con ellos;
y después de la cena, la puesta del sol siendo muy tarde en esa época del año,
llamaron a los sirvientes de la familia (que eran
Cuáqueros) y todos nos sentamos en silencio.
Pero no teníamos mucho tiempo sentados,
cuando Edward Burrough empezó a hablar entre nosotros.
Y aunque no habló por mucho tiempo, lo que dijo tocó, según supongo,
el nervio religioso de mi padre, como dice el dicho.
Y él,
habiendo sido religioso desde joven (aunque no tenía
una estrecha unión con ninguna persuasión),
y valorándose a sí mismo por el conocimiento que estimaba
tener de las diferentes doctrinas de cada denominación,
pensó que en ese momento tenía una buena oportunidad para mostrar su conocimiento,
y entonces comenzó a hacer objeciones contra lo que había sido dicho.
El tema de la conversación era la gracia universal
y gratuita de Dios para con toda la humanidad.
A eso él se opuso con el principio calvinista de la predestinación particular y personal.
Pero en su intento de defender esa indefendible doctrina,
muy pronto se halló más perdido de lo que esperaba.
Edward Burrough no le dijo mucho al respecto,
aunque lo que dijo fue directo al grano y convincente.
Pero luego intervino James Nayler,
y manejó el tema con tanta perspicacia y evidente demostración,
que su razonamiento parecía irresistible; y supongo que mi padre lo vio así,
lo que hizo que rápidamente estuviera dispuesto a dejar la conversación.

En cuanto a Edward Burrough, era un joven vivaz, con facilidad para hablar,
y podría haber sido, por todo lo que yo sabía en ese entonces, un erudito,
lo que me hizo admirar menos su forma de razonar.
Pero lo que salió de la boca de James Nayler tuvo mayor impacto sobre mí,
porque él se veía como un simple y humilde hombre de campo,
ya que tenía la apariencia de un agricultor o de un pastor.

Al ver que mi papá no había sido capaz de mantener la discusión a su favor,
ellos tampoco estuvieron dispuestos a llevarla en extremo a su favor,
sino que tratándolo con suavidad y gentileza, después de un rato dejaron la conversación,
y luego nos retiramos a nuestras respectivas habitaciones.

La mañana siguiente nos preparamos para regresar a casa, a saber, mi padre,
mi hermana menor y yo;
porque mi hermana mayor se había ido antes en una diligencia a Londres.
Y cuando comenzamos a salir, después de habernos despedido de nuestros amigos,
ellos nos acompañaron a la puerta,
donde Edward Burrough nos habló unas pocas palabras a cada uno individualmente,
según el sentido que tenía de nuestras diferentes condiciones.
Y luego de que nos fuimos, cuando ellos regresaron a la casa,
los Penington le preguntaron qué pensaba de nosotros.
Él les respondió (como ellos me contaron después) de esta manera: "`En cuanto al anciano,
está establecido en sus opiniones, y la joven es superficial e indiferente;
pero el joven ha sido alcanzando, y le puede ir bien si no lo pierde.`"
Y sin duda, las palabras que me había hablado,
o más bien el Espíritu por medio del cual las había hablado,
se apoderó de mí tan fuertemente, que sentí que me invadieron la tristeza y la angustia,
aunque no entendía con claridad por qué estaba angustiado.
No sabía qué me afligía, pero sabía que era algo fuera de lo normal,
y mi corazón estaba muy pesado.

Me di cuenta de que no le sucedía lo mismo a mi padre, ni a mi hermana;
porque mientras cabalgaba detrás del coche, podía escucharlos conversar placenteramente.
Pero ellos no pudieron discernir lo que me estaba pasando, porque al ir a caballo,
me mantuve fuera de su vista.

Ya era de noche cuando llegamos a casa, y al siguiente día, que era primer-día,
fui en la tarde a escuchar al ministro de Chinner.
Esa fue la última vez que fui a oír a alguien en ese oficio.
Después del sermón fui con el ministro a su casa,
y en la conversación abierta que solía tener con
él debido a cierta cercanía que había entre nosotros,
le comenté dónde había estado, con quiénes había estado,
y qué observaciones me había hecho respecto a la ocasión.
Parecía que él sabía tan poco de ellos como yo antes,
pero cortésmente se abstuvo de hacer malos comentarios acerca de ellos.

Deseaba asistir a otra reunión de los Cuáqueros, por lo tanto,
le pedí al siervo de mi padre que averiguara si había
alguna en los alrededores del condado.
Él me dijo que había oído en casa de Isaac Penington,
que el próximo jueves habría una reunión en High-wiccomb.
Así que fui para allá, aunque el lugar quedaba a siete millas de distancia.
Y para que otros pensaran que me había ido de caza
dejé que mi galgo corriera al lado de mi caballo.

Cuando llegué al lugar y dejé mi caballo en una posada,
no tenía idea de cómo encontrar la casa en la que se celebraría la reunión.
No sabía dónde estaba y me daba vergüenza preguntar al respecto.
Por lo tanto, luego de haberle pedido al caballerizo que cuidara mi perro,
salí a la calle y me paré en la puerta principal, preguntándome qué camino tomar.
Pero no había pasado mucho tiempo antes de ver a un hombre cabalgando por la calle,
a quien recordaba haber visto antes en la casa de Isaac Penington,
y que dejó su caballo en la misma posada.
Por lo tanto, decidí seguirlo suponiendo que iba a la reunión, como en efecto hizo.

Al llegar a la casa (que resultó ser la de John Raunce)
vi a las personas sentarse juntas en una sala exterior.
Por lo tanto, entré y me senté en el primer asiento vacío,
al final de una banca justo al lado de la puerta,
con mi espada a mi lado y vistiendo ropa negra,
lo que atrajo algunas miradas sobre mí. No pasó mucho
tiempo antes de que alguien se levantara y hablara,
a quien más adelante llegué a conocer bien.
Su nombre era Samuel Thornton; y lo que habló fue muy adecuado y útil para mí,
porque llegó a mi corazón como si hubiera sido dirigido a mí.

Tan pronto como terminó la reunión y las personas comenzaron a levantarse,
estando yo al lado de la puerta, salí rápidamente y me apresuré hacia la posada,
y regresé en seguida a casa en mi caballo;
y hasta donde puedo recordar mi padre no notó que me había salido.

Esta segunda reunión fue como remachar un clavo;
al confirmar y afirmar en mi mente esos buenos principios
que habían calado en mí en la reunión anterior.
Mi entendimiento comenzó a abrirse y sentí algunos movimientos en mi pecho,
que tendían a la obra de una nueva creación en mí. La angustia general y confusión
mental que por algunos días habían permanecido fuertemente sobre mí y me oprimían
sin tener un entendimiento claro de la causa particular por la que venían,
comenzaron a desaparecer en aquel momento,
y algunos destellos de luz comenzaron a levantarse en mí,
que me permitieron ver mi estado y condición interior para con Dios.
La luz,
que antes había resplandecido _en_ mis tinieblas (cuando las tinieblas no podían comprenderla),
comenzó a resplandecer _de_ las tinieblas,
y en cierta medida me dio a conocer qué era lo que antes
me había nublado y traído sobre mí esa tristeza y angustia.
Me di cuenta,
de que aunque había sido preservado en gran medida de las
inmoralidades y de las peores contaminaciones del mundo,
el espíritu del mundo había reinado en mí hasta ese momento,
y me había llevado al orgullo, a la adulación, a la vanidad y a la ostentación;
todo lo cual no tenía ningún valor.
Vi que había muchas plantas creciendo en mí que no
habían sido plantadas por el Padre celestial;
y que todas ellas, independientemente del tipo o clase que fueran,
o qué tan agradables parecieran, debían ser arrancadas.

En ese momento toda mi vida anterior comenzó a ser desgarrada,
y mis pecados poco a poco fueron puestos en orden delante de mí. Y aunque
no se veían tan oscuros como los que cometían las personas más impías,
aun así, hallé que todo pecado--tanto el que aparenta ser hermoso y refinado,
como el que es más grosero y repugnante--producía culpa,
y que con la culpa y por la culpa, traía condenación al alma que pecaba.
Sentí esto y estaba muy humillado bajo la conciencia de ello.

También comencé a recibir una nueva ley, una ley interna, añadida a la ley externa,
a saber,
"`la ley del Espíritu de vida en Cristo Jesús,`" la cual obraba en mí contra todo mal,
no solo en mis acciones y palabras, sino también en mis pensamientos;
de modo que todo fue llevado a juicio, y el juicio pasó sobre todas las cosas.
Así que, ya no pude seguir en mis caminos pasados y en mi curso de vida anterior,
porque cada vez que lo intentaba,
el juicio se apoderaba de mí. De este modo le plació
al misericordioso Señor tratar conmigo,
de manera muy similar a la que había usado para tratar a Su pueblo Israel en el pasado;
porque cuando transgredían Su ley justa y Su profeta los llamaba a volverse,
Él les ordenaba que primero "`dejaran de hacer lo
malo`" y luego que "`aprendieran a hacer el bien,`"^
footnote:[Isaías 1:16-17]
antes de que les permitiera razonar^
footnote:[Isaías 1:18 LBLA]
con Él,
y antes de que les impartiera los efectos de Su gratuita
misericordia (Véase Isaías capítulo 1).

Esta ley interna y espiritual--la ley del Espíritu de vida en Cristo Jesús--me requería
ahora que "`quitara la iniquidad de mis obras,`" y "`dejara de hacer lo malo.`"
Y en cuanto a los males particulares que debía quitar y dejar de hacer,
la medida de luz divina (que en ese momento se manifestaba en mí) comenzó a mostrármelos;
y todo lo que la luz manifestaba como malo, era juzgado.

Y así comenzó a construirse un camino delante de mí para que caminara en él^
footnote:[Isaías 57:14; 62:10 LBLA]--un camino directo y simple; tan simple,
que un viajero, sin importar cuán débil y sencillo fuera,
aunque torpe en la sabiduría y juicio del mundo,
no podría extraviarse mientras siguiera andando en él;^
footnote:[Isaías 35:8]
ya que el extravío únicamente ocurre cuando el hombre se sale de él. Y
vi que ese _camino_ era la medida de luz divina que se manifestaba en mí,
por la cual se me daba a conocer la iniquidad de mis obras.

Y entonces vi, por esa luz divina,
que aunque no tenía necesidad de quitar los pecados de inmundicia, libertinaje,
blasfemia y otras contaminaciones comunes del mundo,
porque gracias a la gran bondad de Dios y a una educación
civilizada había sido preservado de esos males tan evidentes;
aun así, tenía muchos otros males que quitar y dejar de hacer.
De hecho,
algunos ni siquiera eran considerados males por "`el mundo que yace en maldad;`"^
footnote:[1 Juan 5:19 Reina Valera de Gómez]
pero por la luz de Cristo me fueron manifestados como males,
y así fueron condenados en mí; como por ejemplo,
los frutos y efectos del orgullo que se manifestaban
en la vanidad y ostentación de mi apariencia.
Por desgracia, yo me había deleitado mucho en eso,
tanto como mis recursos me lo habían permitido.
Por lo tanto, se me requirió que quitara y dejara de hacer todas esas cosas;
y el juicio se mantuvo fuertemente sobre mí hasta que lo hice.
Y así, en obediencia a la ley interna que concordaba con la externa (Véase 1 Timoteo 2:9;
1 Pedro 3:3; 1 Timoteo 6:8; Santiago 1:21),
quité de mi vestimenta todos los adornos innecesarios como encajes,
cintas y botones inútiles, que realmente no servían para nada,
sino que eran usados únicamente como "`adornos,`" y también dejé de usar anillos.

También se me requirió que dejara la costumbre de
dirigirme a los hombres con títulos aduladores.
Ese era un mal al que había sido muy adicto y era considerado un completo artista en ello.
Así que a partir de ese momento,
no me atreví a decir "`caballero,`" "`maestro,`" "`mi señor`" o "`señora`" a ninguna persona,
ni a decir "`vuestro humilde servidor`" a ninguno
con el que no tuviera una relación real de siervo;
algo que nunca había sido de ningún hombre.

Mostrar respeto a ciertas personas descubriendo mi cabeza y haciendo
una reverencia al inclinar mi rodilla o mi cuerpo a manera de saludo,
era una práctica que había usado mucho.
Esta es una de las costumbres vanas del mundo,
introducida por el espíritu del mundo en el lugar del verdadero honor.
Vi que era una falsa actuación,
utilizada en engaño como una señal de respeto a personas
que realmente no se respetaban entre sí. Además,
ese gesto es una forma o señal apropiada del honor
divino que todos le debemos rendir al Dios Todopoderoso,
y que todos los Cristianos, de cualquier denominación,
usan cuando le presentan sus oraciones, y por lo tanto, no deben darse a los hombres.
Hallé que ese era otro mal que había estado cometiendo por mucho tiempo, y por eso,
ahora se me requería que lo dejara de hacer.

También estaba muy acostumbrado a la forma corrupta
e incorrecta de hablar en plural a una sola persona,
diciendo "`ustedes`" a uno en lugar de "`tú,`" de forma contraria al lenguaje puro,
simple y sencillo de la Verdad: a saber,
"`tú`" a una sola persona y "`ustedes`" a más de una.
Desde el más antiguo registro de los tiempos,
esta había sido siempre la forma usada por Dios para dirigirse a los hombres,
y por los hombres a Dios, así como también entre ellos, hasta que hombres corruptos,
por fines corruptos, en los últimos y corruptos tiempos, para adular y lisonjear,
introdujeron esa forma falsa y absurda de decirle "`ustedes`" a una sola persona;
la cual, ha corrompido el lenguaje moderno desde entonces,
y ha envilecido mucho los espíritus de los hombres y depravado sus costumbres.^
footnote:[En ese tiempo en la historia,
el uso correcto y simple de "`tú`" y "`usted`" para una
sola persona empezó a dar paso a "`vosotros`" y "`ustedes.`"
La mayoría de los angloparlantes modernos desconocen que las palabras
"`you`" y "`your`" eran originalmente pronombres _plurales_ que se
utilizaban sólo para dirigirse a dos o más personas,
mientras que "`thee`" y "`thou`" se usaban para dirigirse a una sola persona singular.
En los años 1600,
se puso de moda (originalmente con el fin de mostrar honor o adulación)
utilizar el plural "`you`" y "`your`" ("`ustedes`" y "`vosotros`")
para dirigirse a personas de mayor estatus social,
mientras que "`thee`" y "`thou`" ("`tú`" y "`usted`") se reservaban para los sirvientes,
los niños o las personas de menor posición social o económica.
Los amigos se ciñeron a lo que entonces se consideraba "`lenguaje simple`" (utilizar
los pronombres "`thee`" y "`thou`" ("`tú`" y "`usted`") para referirse a una persona,
y "`you`" y "`your`" ("`ustedes`" y "`vosotros`") para dos o más),
en lugar de mostrar preferencia al dirigirse a ciertos individuos en plural.]
Esas y muchas malas costumbres más,
que habían brotado en la noche de oscuridad y gran
apostasía de la Verdad y de la verdadera religión,
ahora, mediante el resplandor interior de ese rayo puro de luz divina en mi conciencia,
estaban siendo reveladas gradualmente en mí como cosas que debía dejar de hacer,
evitar y contra las cuales debía permanecer como un testigo.

Pero el enemigo obró tan sutil y poderosamente en mi parte débil,
que me persuadió a creer que debía hacer una diferencia
entre mi padre y el resto de los hombres en esas cosas,
dejando de usar esas señales de respeto con otros, y sin embargo,
seguir usándolas con él, ya que él era mi padre.
Y esa estratagema del enemigo prevaleció tanto en mí,
(por temor a hacer algo malo al dejar de rendirle a mi padre
cualquier tipo de respeto u honor que le correspondiera),
que estando así engañado,
me mantuve por un tiempo dirigiéndome a él de la misma manera de siempre,
tanto con respecto al lenguaje como también a los gestos de respeto y honor.
Y mientras lo hice,
estando delante de él con la cabeza descubierta y hablándole en el lenguaje acostumbrado,
él nunca expresó ningún disgusto hacia mí.

Pero en cuanto a mí y a la obra que había comenzado en mí,
pronto me di cuenta de que no era suficiente "`dejar de
hacer lo malo;`" a pesar de que ese era un buen paso.
Tenía otra lección por delante,
"`aprender a hacer el bien,`" lo que de ninguna manera podría hacer,
hasta que me hubiera entregado sinceramente, con pleno propósito de corazón,
a dejar de hacer todo lo malo.
Y cuando lo hice, el enemigo se aprovechó de mi debilidad para desviarme por otro camino.

Porque debí haber esperado en la luz la dirección
y la guía en el camino de hacer el bien,
y no haberme movido sin el Espíritu divino (del cual,
le había placido al Señor darme una manifestación para provecho^
footnote:[1 Corintios 12:7]), pero el enemigo, disfrazándose como ángel de luz,
se ofreció entonces a ser mi guía y líder en la ejecución de ejercicios religiosos.
Y yo, sin conocer en ese entonces las maquinaciones de Satanás,
y estando deseoso de hacer algún servicio agradable a Dios,
me entregué con demasiada facilidad a la guía de mi enemigo,
en lugar de a la de mi amigo.

Entonces él, fomentando el fervor y celo de mi espíritu,
me impulsó a realizar actos religiosos en mi propia voluntad,
en mi propio tiempo y en mis propias fuerzas--cosas que en sí mismas eran buenas,
y que habrían sido provechosas para mí y aceptables para el Señor,
si las hubiera realizado en Su voluntad, en Su tiempo y en el poder que Él da.
Pero al haber hecho esas cosas en la voluntad del hombre y por la incitación del maligno,
no es de extrañar que me hicieran daño en lugar de bien.

Leía mucho la Biblia y me ponía tareas de lectura;
exigiéndome a mí mismo leer muchos capítulos,
algunas veces un libro entero o largas epístolas a la vez.
Pensaba que eso era utilizar bien el tiempo,
aunque no era mucho más sabio con todo lo que leía;
porque lo leía muy apresuradamente y sin el verdadero Guía, el Espíritu Santo,
el único que podía abrir mi entendimiento y darme
un verdadero sentido de lo que estaba leyendo.
Oraba a menudo y alargaba mis oraciones por mucho tiempo,
estableciendo ciertos tiempos para orar y un cierto número de oraciones que decir al día;
sin embargo, durante ese tiempo no sabía lo que era la oración verdadera.
Porque la verdadera oración no consiste en palabras,
incluso cuando las palabras sean habladas en los movimientos del Espíritu Santo;
sino más bien en la respiración del alma hacia el Padre
celestial mediante la operación del Espíritu Santo,
que intercede por nosotros--a veces con palabras y a veces solo
con gemidos y suspiros--que el Señor misericordioso oye y responde.

Ese culto voluntario^
footnote:[Colosenses 2:23]--que es toda adoración realizada en la voluntad del
hombre y no en los movimientos del Espíritu Santo--fue muy perjudicial para mí,
y un tropiezo para mi crecimiento espiritual en el camino de la verdad.
Pero mi Padre celestial, quien conocía la sinceridad de mi alma delante de Él,
y el deseo sincero que tenía de servirle, tuvo compasión de mí;
y a su debido tiempo le plació bondadosamente iluminar más mi entendimiento,
y abrir en mí un ojo para discernir al espíritu falso y su forma de obrar, del verdadero;
y rechazar al primero y aferrarme al último.

Pero aunque el enemigo había obtenido algunas ventajas sobre mí con su sutileza, yo,
sin embargo,
seguí adelante y persistí firmemente en mi resolución
piadosa de dejar y negar aquellas cosas,
que en ese entonces estaba convencido en mi consciencia que eran malas.
Y por esa razón rápidamente vino sobre mí una gran prueba.
Porque como se acercaban la Sesiones Trimestrales Generales para la paz,
y mi padre quería evitar hacer ese sucio viaje,
me ordenó que me levantara temprano y fuera a Oxford,
y entregara las obligaciones de registros que había contraído; y que además,
le trajera un reporte de qué jueces habían estado en el tribunal,
y cuáles habían sido los principales casos que se habían presentado ante ellos;
todo lo cual él sabía que yo podía hacer,
ya que a menudo lo había acompañado en esos servicios.

Pero yo, que conocía mi situación mucho mejor que él,
sentí un peso sobre mí tan pronto como pronunció las palabras.
Porque inmediatamente vi que eso me generaría una gran prueba.
Sin embargo,
no habiendo resistido nunca su voluntad en nada que fuera lícito (como era el caso),
no intenté poner ninguna excusa.
Y después de ordenar que un caballo estuviese listo para mí temprano por la mañana,
me fui a la cama, sintiendo un gran conflicto en mi pecho.
Porque el enemigo vino como un río y me presentó muchas dificultades,
exagerándolas al máximo posible,
al describirlas como montañas que nunca sería capaz de superar.
Desgraciadamente, la fe que podía quitar montañas y echarlas al mar,
todavía era muy pequeña y débil en mí.

Él puso en mi mente,
no solo cómo debía comportarme en la corte y realizar el asunto por el que era enviado,
sino también cómo debía actuar con mis conocidos,
de los cuales tenía muchos en la ciudad y con quienes antes había sido muy jovial,
dado que ahora no podía quitarme mi sombrero, ni inclinarme ante ninguno de ellos,
ni decirles sus títulos de honor (como son llamados),
ni usar el lenguaje corrupto de "`ustedes`" con ninguno de ellos,
sino que debía atenerme al lenguaje sencillo del "`tú.`" Muchos
pensamientos de esta naturaleza daban vueltas en mi mente,
los cuales eran lanzados por el enemigo para desanimarme y abatirme.
Y no tenía a nadie a quien volverme para recibir consejo o ayuda,
sino únicamente al Señor; por tanto,
derramé ante Él mis súplicas con fervientes clamores y suspiros del alma,
rogándole que Él, en quien se encontraba todo el poder,
me capacitara para atravesar esa gran prueba y me mantuviera fiel a Él en ella.
Y después de un tiempo, le plació a Dios calmar mi mente y pude descansar.

A la mañana siguiente me levanté temprano y sentí mi espíritu bastante calmado y quieto,
aunque con un temor sobre mí de deslizarme y dejar caer el testimonio que debía dar.
Y mientras cabalgaba, un constante clamor al Señor resonaba dentro de mí: "`¡Oh mi Dios,
mantenme fiel, sin importar lo que me acontezca! ¡No permitas que sea arrastrado al mal,
no importa cuánto desdén y desprecio sea echado sobre mí!`"

De esta manera fue ejercitado mi espíritu en el camino casi todo el tiempo.
Y cuando estaba a una milla o dos de la ciudad, ¡a quién me encuentro saliendo de ella,
sino a Edward Burrough!
Yo cabalgaba con un gorro de invierno,^
footnote:[Un gorro de invierno que tenía solapas para proteger el rostro del frío.]
un atavío que era más común en ese entonces que ahora, y él también lo llevaba;
y debido a que el clima estaba demasiado frío,
ambos habíamos bajado nuestras solapas para cubrir nuestros
rostros del frío. Por esa razón no pudimos reconocernos,
sino que pasamos de largo sin notarnos hasta unos pocos días después,
cuando al encontrarnos otra vez y observar nuestra ropa,
recordamos dónde nos habíamos visto recientemente.
Entonces pensé dentro de mí: "`¡Oh,
cómo me hubiera alegrado haber recibido de él una palabra de aliento y consejo,
cuando me encontraba bajo ese fuerte ejercicio interno!`"
Pero el Señor vio que no era bueno para mí,
que mi confianza debía estar completamente puesta sobre Él y no sobre el hombre.

Después de guardar mi caballo,
fui directamente a la sala donde se llevaban a cabo las sesiones de la corte,
y no había pasado mucho tiempo antes de que un grupo
de mis antiguos conocidos me viera y se acercara.
Uno de ellos era un erudito que llevaba su toga; otro un médico de esa ciudad,
ambos compañeros de clases y residencia en la escuela de Thame.
El tercero era un caballero de campo con quien había tenido
una larga y estrecha relación. Cuando se me acercaron,
me saludaron de la manera usual, quitándose sus sombreros, inclinándose y diciendo:
"`Vuestro humilde servidor, señor;`" esperando, sin ninguna duda,
que yo hiciera lo mismo.
Pero cuando me vieron permanecer firme, sin mover mi sombrero,
ni doblar mi rodilla en señal de cumplido hacia ellos,
se sorprendieron y primero se miraron entre sí, luego me miraron a mí,
y luego nuevamente entre ellos por un momento, sin decir una palabra.
Finalmente, el médico, un joven vivaz, que era el que estaba más cerca de mí,
dándome una palmada en el hombro de manera familiar y sonriéndome dijo:
"`¡Qué Tom! ¿Un Cuáquero?`"
A lo que respondí pronta y alegremente: "`Sí, un Cuáquero.`"
Y a medida que las palabras salían de mi boca,
sentí que brotaba una alegría en mi corazón;
porque me dio gozo no haber sido arrastrado a conformarme a ellos,
y se me había concedido esa fuerza y denuedo para
confesar que era uno de ese pueblo despreciado.

No se quedaron mucho tiempo conmigo, ni dijeron nada más que yo recuerde;
sino que mirándose unos a otros algo confundidos, después de un rato se despidieron,
partiendo de la misma manera ceremoniosa con la que habían llegado.

Después de que se fueron,
caminé un rato por la sala y me acerqué al tribunal,
para observar qué jueces estaban en el estrado y qué asuntos tenían ante ellos.
Hice eso con temor, no de lo que ellos pudieran o quisieran hacerme,
sino de que alguno me sorprendiera e inadvertidamente
me arrastrara a algo de lo que debía abstenerme.

No pasó mucho tiempo antes de que el tribunal levantara la sesión para ir a cenar,
y usé ese tiempo para visitar al secretario de paz en su casa, a quien conocía bien.
Tan pronto llegué a la habitación en la que él estaba,
se acercó y me saludó según su costumbre;
porque tenía gran respeto por mi padre y un afectuoso cariño por mí. Y
aunque al principio estaba algo sorprendido por mi conducta y lenguaje,
aun así, me trató muy civilmente, sin ningún reproche o burla.
Le entregué las obligaciones de registro que mi padre había enviado,
y después de terminar el asunto por el que había ido,
salí y me fui a mi posada a descansar, para luego regresar a casa.
Pero cuando estaba listo para tomar mi caballo, al mirar hacia la calle,
vi a dos o tres jueces parados justo en el camino por el que iba a cabalgar.
Eso me produjo una nueva preocupación, porque sabía que si me veían,
me reconocerían. Y concluí que si me reconocían,
me detendrían para preguntar por mi padre;
y dudaba si podría permanecer fiel a mis convicciones.

Esa duda trajo debilidad sobre mí,
y esa debilidad me llevó a idear cómo podría evitar esa prueba.
Conocía muy bien la ciudad, y recordé que había otra ruta, la cual,
aunque se desviaba un poco de mi camino,
me sacaría de la ciudad sin pasar por donde estaban esos jueces; sin embargo,
no estaba dispuesto a tomarla.
Por lo tanto, me esperé un rato,
con la esperanza de que ellos se separaran o se fueran
a otro lugar que no estuviera en mi camino.
Pero cuando había esperado hasta sentirme inquieto por perder tanto tiempo,
y habiendo entrado en razonamientos con carne y sangre,
la debilidad prevaleció sobre mí y tomé la otra ruta;
lo cual trajo angustia y dolor sobre mi espíritu por haber evadido la cruz.

Pero el Señor me miró con ojos tiernos, y al ver que mi corazón era recto para con Él,
y que lo que había hecho había sido meramente por debilidad y temor a caer,
y que yo estaba consciente de mi error y me lamentaba por ello,
le plació bondadosamente pasarlo por alto y hablarme paz otra vez.
Cuando salí por la mañana,
mi corazón había estado lleno de oraciones anhelantes al Señor,
rogándole que tuviera misericordia de mí,
y me sostuviera y guardara a través de ese día de prueba.
Y luego, a mi regreso por la noche, antes de llegar a casa,
mi corazón estaba lleno de agradecimiento y alabanzas
a Él por Su gran bondad y favor para conmigo,
al haberme preservado y guardado hasta ese momento
de caer en algo que hubiera deshonrado Su santo nombre,
el nombre que había tomado sobre mí.

Pero a pesar de que había sucedido así conmigo,
y de que en una buena medida había encontrado paz y aceptación en el Señor,
conforme mi obediencia a las convicciones que había recibido de Su Espíritu Santo en mí;
aun así, el velo no había sido quitado completamente,
porque todavía permanecía una nube sobre mi entendimiento
con respecto a mi conducta hacia mi padre.
Y el concepto que el enemigo había introducido en mi mente--que
debía hacer una diferencia entre él y todos los demás debido a
la relación paternal--todavía prevalecía en mí. Por lo tanto,
cuando llegué a casa,
me acerqué a mi padre y me paré delante de él con mi cabeza descubierta como solía hacerlo,
y le di un reporte detallado de los asuntos de forma tal,
que al no observar ninguna alteración en mi conducta hacia él,
no encontró ningún motivo para sentirse ofendido por mí.

Por un tiempo antes de eso,
había sentido un deseo ferviente de ir otra vez a la casa de Isaac Penington.
Y me comencé a preguntar si mi padre,
cuando supiera que me inclinaba a formar parte del pueblo llamado
Cuáqueros (como estaba seguro de que lo haría en poco tiempo),
seguiría permitiéndome usar sus caballos.
Por esa razón, la mañana que fui a Oxford,
le di instrucciones a uno de sus siervos para que
fuera ese día a un caballero conocido mío,
que sabía que tenía un caballo que estaba dispuesto a prestar, y que pidiera,
en mi nombre, que me lo enviara.
Así lo hizo, y lo hallé en el establo cuando llegué a casa.

En ese caballo planeaba ir a la casa de Isaac Penington al día siguiente; y para ello,
me levanté temprano y me preparé para el viaje.
Pero dado que deseaba rendirle el debido respeto a mi padre,
y no ir sin su consentimiento, o al menos sin su conocimiento,
envié a un siervo (porque mi padre todavía no se había despertado) para
que le informara que tenía la intención de ir a casa de Isaac Penington,
y que deseaba saber si él necesitaba que hiciera algún servicio.
Me mandó a decir que deseaba hablar conmigo antes de que me fuera,
y que quería que subiera a verle; lo cual hice, y me paré junto a su cama.

Entonces en un tono suave y gentil dijo:
"`Entiendo que tienes la intención de ir a casa del Sr. Penington.`"
Yo respondí: "`La tengo.`"
"`¿Bueno?,`" dijo él,
"`¿me pregunto por qué? Sabes que estuviste ahí hace apenas unos pocos días,
y a menos que tengas negocios con ellos, ¿no crees tú que parecerá extraño?`" Respondí:
"`No lo creo.`"
"`Quizás,`" dijo él, "`los cansarás con tu compañía y te volverás una carga para ellos.`"
"`Si veo algo de eso,`" respondí, "`me quedaré por poco tiempo.`"
"`Pero,`" dijo él, "`¿puedes proponer algún tipo de negocio, más que una mera visita?`"
"`Sí,`" dije yo, "`no solo me propongo verlos, sino tener una conversación con ellos.`"
"`¿Por qué?,`" dijo en un tono más rudo,
"`espero que no estés inclinado a unirte a su religión`" "`En verdad,`" respondí,
"`ellos me agradan mucho y su religión también, hasta donde la he podido entender;
y quiero ir a verlos para poder entenderla mejor.`"

Entonces mi padre comenzó a enumerar una lista de fallas contra los Cuáqueros,
diciéndome que eran un pueblo grosero y descortés,
que se negaban a rendirles respeto u honor civil a sus superiores y a los magistrados,
que sostenían muchos principios peligrosos, que era un pueblo inmodesto y sinvergüenza,
y que uno de ellos se había desnudado completamente,
y había andado de esa manera indecorosa por las calles,
en las ferias y en los días de mercado en las grandes ciudades.

A todas las acusaciones,
solo respondí que quizás los habían acusado falsamente o habían sido malinterpretados,
como algunas veces había ocurrido hasta con las mejores personas.
Pero a su última acusación, la de andar desnudo, una respuesta particular,
a modo de ejemplo, fue traída a mi mente y puesta en mi boca justo en ese momento,
en la cual no había pensado antes; el ejemplo de Isaías,
que había andado desnudo entre el pueblo por un largo
tiempo (Isaías 20:4). "`Ah,`" dijo mi padre,
"`pero debes considerar que él era un profeta del Señor,
y tenía un mandamiento expreso de Dios para hacerlo.`"
"`Sí, señor,`" respondí, "`así lo considero;
pero también considero que los judíos entre quienes vivía,
no lo reconocían como un profeta,
ni creían que tuviera un mandamiento expreso de Dios para lo que hacía.`" Y añadí,
"`¿cómo sabemos que ese Cuáquero no es un profeta también,
con un mandamiento para hacer lo que hizo, por alguna razón que no entendemos?`"

Eso dejó a mi padre sin argumentos;
así que dejando caer sus acusaciones contra los Cuáqueros, solo dijo:
"`Quisiera que no fueras tan pronto,
sino que te tomaras un poco de tiempo para considerarlo.
Puedes visitar al Sr. Penington en otro momento.`"
"`No, señor,`" respondí, "`por favor no estorbes mi partida en este momento,
porque tengo un deseo tan grande de ir que no sé bien como contenerme.`"
Y mientras decía esas palabras, me retiré gentilmente a la puerta de la recámara,
y luego bajando las escaleras apresuradamente, me fui directamente al establo,
y hallando mi caballo ya con el freno puesto, me monté rápidamente y me fui,
no fuera a ser que recibiera una contraorden.

Esa conversación con mi padre retrasó un poco mi viaje,
y siendo que estaba a quince millas de distancia,
los caminos eran malos y mi caballo pequeño, no llegué hasta la tarde.
Y cuando escuché del siervo que tomó mi caballo que
en ese momento había una reunión en la casa,
ya que había una reunión semanal cada cuarto día, me apresuré a entrar.
Conocía bien las habitaciones,
así que fui directamente al pequeño salón donde encontré
unos pocos Amigos sentados en silencio,
y me senté entre ellos muy satisfecho, aunque no se dijo ninguna palabra.

Cuando terminó la reunión, y los que no eran parte de la familia se habían ido,
me dirigí a Isaac Penington y a su esposa, quienes me recibieron cortésmente;
pero al no saber en qué ejercicios internos había estado, y todavía estaba,
ni haber escuchado nada de mí desde la última vez
que había estado ahí con una vestimenta diferente,
no se apresuraron a "`imponer sus manos sobre mí con ligereza,`"^
footnote:[1 Timoteo 5:22 Una advertencia de Pablo de no aprobar o recomendar
a alguien a la hermandad o el ministerio sin la debida precaución.]
lo cual noté y no me desagradó. Pero cuando llegaron a ver un cambio en mí,
no solo en mi forma de vestir, sino en mi conducta y discurso,
y además en mi semblante (porque los ejercicios por
los que había pasado y bajo los cuales todavía estaba,
habían impreso un carácter visible de seriedad en mi rostro),
se mostraron demasiado amables y tiernos conmigo.

En ese momento estaba con la familia una Amiga--cuyo nombre era Anne Curtis,
la esposa de Thomas Curtis de Reading--que había ido a visitarlos,
y particularmente a ver a la hija de Mary Penington, Gulielma,
que había estado enferma de viruela desde la última vez que había estado ahí.
Noté algunas conversaciones privadas y susurros entre Mary Penington y esta Amiga,
y me dio la impresión de que tenían que ver conmigo.
Por lo tanto,
me tomé la libertad de preguntarle a Mary Penington si mi
visita había ocasionado alguna inconveniencia en la familia.
Ella me preguntó si a mí me había dado viruela, y le respondí que no.
Entonces me dijo que a su hija le había dado recientemente,
y que aunque se había recuperado bien, todavía no había estado abajo entre ellos,
pero tenía la intención de bajar y sentarse con ellos en el salón esa noche.
Eso era lo que habían estado discutiendo.
Le aseguré que siempre me había sentido libre, y en ese momento más que nunca,
de cualquier temor a ese tipo de peligro; y por tanto,
le pedí que permitiera que su hija bajara.
Aunque no parecían muy dispuestas a ceder debido a su preocupación por mí,
mi insistencia prevaleció, y ella bajó después de la cena y se sentó con nosotros.
Y aunque las marcas de la enfermedad todavía estaban frescas en ella, aun así,
no causaron ninguna impresión en mí, pues la fe mantuvo fuera todo temor.

Pasamos la mayor parte de la noche en retiro,
nuestros espíritus estaban fuerte e internamente vueltos al Señor;
de modo que no hablamos mucho entre nosotros, ni ellos a mí, ni yo a ellos.
Sin embargo, me sentía muy satisfecho en esa quietud,
ya que sentía que mi espíritu se acercaba al Señor
y a ellos en Él. Antes de irme a la cama,
me hicieron saber que habría una reunión en Wiccomb al día siguiente,
y que algunos de la familia asistirían. Me alegré mucho,
ya que tenía un gran deseo de ir a reuniones, y esa me resultaba muy conveniente,
porque estaba en mi ruta a casa.
A la mañana siguiente Isaac Penington y Anne Curtis fueron a la reunión,
y yo los acompañé.

En Wiccomb nos encontramos con Edward Burrough, quien había llegado de Oxford,
donde yo lo había visto unos días antes,
cuando ambos llevábamos nuestros gorros de invierno
y nos habíamos cruzado en el camino sin reconocernos.
Pero en ese momento nos dimos cuenta de que nos habíamos encontrado recientemente.

Esa era una reunión mensual,
compuesta principalmente de Amigos que llegaban de varias partes de los alrededores;
por lo tanto, era bastante grande.
Se llevó a cabo en un salón de la casa de Jeremiah Stevens,
ya que la sala donde nos habíamos reunido antes en la casa de John Raunce,
era demasiado pequeña para albergarnos a todos.
Esa fue una reunión buena para mí. El ministerio de Edward
Burrough fluyó entre nosotros con vida y poder,
y la asamblea fue cubierta con él. Yo también, según mi pequeña capacidad,
experimenté una participación en ello.
Porque sentí que algo de ese poder divino obraba en mi espíritu una gran ternura,
no solo confirmándome en el camino que ya había tomado
y fortaleciéndome a seguir adelante en él,
sino también rasgando más el velo y aclarando mi entendimiento
en algunas otras cosas que no había visto antes.
Porque le plació al Señor abrirme los ojos gradualmente,
para que la perspectiva de una obra tan grande y
de muchos enemigos que encarar a la misma vez,
no me desanimara ni me hiciera desmayar.

Cuando la reunión terminó,
los Amigos del pueblo se dieron cuenta de que yo era el
hombre que había estado en su reunión la semana anterior,
a quien en ese momento no conocían. Algunos de ellos se me acercaron y me hablaron amablemente,
y me pidieron que me quedara con ellos; pero Edward Burrough,
que regresaba a casa con Isaac Penington, me invitó a ir con él,
a lo que accedí de buena gana.
Porque el amor que sentía especialmente hacia Edward Burrough,
por cuyo ministerio había recibido ese primer golpe que despertó mi alma,
me había llevado a desear su compañía; y así nos fuimos juntos a caballo.

Pero mi expectativa se vio algo frustrada;
porque esperaba que él me diera tanto la oportunidad como el ánimo para abrirme con él,
y derramar en su seno mis quejas, temores, dudas y preguntas.
Pero él, al estar consciente de que estaba verdaderamente alcanzado,
y que el testigo de Dios se había levantado en mí,
y la obra de Dios había empezado adecuadamente--decidió
dejarme a la guía del buen Espíritu en mí mismo,
el Consejero que podía resolver todas las dudas,
a fin de que no tuviera ninguna dependencia en el hombre.
Por lo tanto, aunque él era naturalmente de actitud y conducta abiertas y libres,
y después fue muy amoroso y cariñoso conmigo siempre,
en ese momento se mantuvo un tanto reservado y solo me mostró una amabilidad común.

Al día siguiente nos separamos, él partió para Londres y yo para mi casa,
bajo un gran peso y ejercicio sobre mi espíritu.
Porque en ese momento veía, en y por las nuevas revelaciones de la luz divina en mí,
que el enemigo me había engañado y desviado a través de sus falsos razonamientos,
en cuanto a mi conducta hacia mi padre;
y que el honor debido a los padres no consistía en
descubrirse la cabeza e inclinarse ante ellos,
sino en una obediencia voluntaria a sus mandamientos lícitos,
y en la realización de todos los servicios necesarios para ellos.
Por lo tanto,
como estaba muy angustiado por lo que ya había hecho en ese caso (aunque fue por ignorancia),
sentí claramente que ya no podía continuar haciéndolo sin
atraer sobre mí la culpa por la desobediencia voluntaria,
lo que yo bien sabía traería tras de sí el desagrado y juicio divino.

En ese momento el enemigo me asaltó nuevamente,
poniendo delante de mí el peligro que correría si
provocaba a mi padre a ser severo conmigo,
y quizás a que me echara totalmente.
Pero clamé al Señor y Él me ayudó en esa tentación,
y me dio fe para creer que Él me sostendría a través de
cualquier cosa que pudiera ocurrirme a causa de eso.
Por tanto resolví, en la fuerza que Él me daría, ser fiel a Sus requerimientos,
sin importar lo que sucediera.

Así, luchando bajo varios ejercicios en el camino, finalmente llegué a mi casa,
esperando encontrarme con una dura recepción por parte de mi padre.
Pero cuando llegué a casa, hallé que mi padre no estaba.
Por lo tanto, me senté junto al fuego de la cocina,
manteniendo mi mente retirada y vuelta hacia el Señor,
con suspiros de espíritu a Él rogándole que me preservara de caer.

Después de un tiempo escuché llegar el coche, lo que me hizo sentir un poco de miedo,
y me invadió una especie de temblor.
Pero para el momento en que él se bajó del coche y entró a la casa,
yo me había recuperado bastante bien.
Apenas lo vi, me levanté, di uno o dos pasos hacia él,
y con mi sombrero todavía puesto le dije:
"`Isaac Penington y su esposa te mandan saludos con cariño.`"

Se detuvo para oír lo que dije,
y notando que no estaba delante de él con la cabeza descubierta,
y que usaba la palabra "`te`" hacia él,
con un semblante rudo y un tono que demostraba gran desagrado, solo dijo:
"`¡Hablaré con usted en otro momento, señor!`"
Luego, alejándose rápido de mí entró en la sala, y no lo vi más esa noche.

Aunque preveía que se avecinaba una tormenta, cuya percepción me inquietaba, aun así,
la paz que sentí en mi propio pecho,
levantó en mí un agradecimiento al Señor por Su bondadosa mano,
que hasta ese momento me había sostenido a través de esa dificultad.
Y surgieron humildes clamores en espíritu a Él, rogándole que en Su misericordia,
permaneciera a mi lado hasta el final y me sostuviera para no caer.

Mi espíritu anhelaba estar entre los Amigos y en alguna reunión con ellos el primer día,
el cual se acercaba, ya que era la noche del sexto día. Por lo tanto,
habiendo oído que habría una reunión en Oxford, me propuse ir allá al día siguiente,
que era séptimo día. En consecuencia,
luego de pedir que mi caballo estuviera listo a primera hora, me retiré;
por la mañana me levanté y me alisté. Sin embargo, antes de irme,
a fin de actuar con tanta rectitud hacia mi padre como me fuera posible,
le pedí a mi hermana que subiera a su recámara y
le hiciera saber que tenía la intención de ir a Oxford,
y que deseaba saber si tenía alguna tarea para mí que realizar allá. Él
le pidió que me dijera que no me fuera hasta que él hablara conmigo.
Y levantándose inmediatamente, se apresuró a bajar antes de terminar de vestirse.

Apenas me vio con el sombrero puesto,
su pasión hizo que perdiera la razón y me cayó a golpes con sus
dos puños. Y después de desahogar un poco su ira de esa manera,
me quitó el sombrero y lo arrojó lejos.
Luego,
saliendo apresuradamente al establo y viendo el caballo
que yo había tomado prestado listo,
ensillado y con el freno puesto, le preguntó a su siervo de dónde venía el caballo.
Él le dijo que lo había tomado prestado del Sr. Barton, y mi padre respondió:
"`Entonces regrésalo inmediatamente,
y dile al Sr. Barton que por favor no le vuelva a prestar un caballo a mi hijo,
a menos que lleve una nota de mi parte.`"
El pobre hombre, que me amaba mucho, estaba muy dispuesto a poner excusas por mí,
pero mi padre fue muy insistente con su orden,
y estaba tan urgido que no le permitió quedarse para desayunar,
aunque tenía cinco millas de camino por cabalgar;
ni quiso abandonar el establo hasta que vio al hombre montarse en el caballo y marcharse.

Después de eso entró y subió a su habitación para terminar de alistarse,
pensando que me había confinado en la casa, ya que mi caballo no estaba;
porque me gustaba tanto cabalgar, que rara vez iba a pie a algún lugar.
Pero mientras él se vestía en su habitación, cambié mis botas para cabalgar por zapatos,
tomé otro sombrero, y luego,
haciéndole saber a mi hermana (quien me amaba mucho
y en quien podía confiar) adónde pretendía ir,
me fui solo y me alejé caminando hacia Wiccomb, teniendo siete millas que recorrer,
las cuales, sin embargo,
me parecían poco y fáciles por el deseo que tenía de estar entre los Amigos.

Pero mientras viajaba solo--bajo una carga de aflicción por la conciencia
que tenía de la oposición y dificultad que debía esperar de mi padre--el
enemigo aprovechó la oportunidad para asaltarme otra vez,
poniendo una duda en mi mente sobre sí había hecho o no
lo correcto al alejarme de mi padre sin su permiso o conocimiento.
Mi espíritu estaba quieto y en paz antes de que esa pregunta fuera lanzada a mi mente;
pero después, perturbación y angustia cayeron sobre mí, de modo que no sabía qué hacer,
si avanzar o retroceder.
El temor de ofender me inclinaba a regresar,
pero el deseo de estar en la reunión con los Amigos me impulsaba a seguir adelante;
así que permanecí quieto por un tiempo para considerar
y sopesar las cosas tan bien como pudiera.
Me dio paz ver que no había dejado a mi padre con
ninguna intención de desobedecerlo ni de irrespetarlo;
sino meramente en obediencia a la inclinación que
el Espíritu había puesto en mí--la cual,
estaba persuadido que venía del Señor--a unirme a Su pueblo en adoración a Él;
y eso me hizo sentir tranquilo.

Pero luego el enemigo, para inquietarme otra vez objetó:
¿Cómo una inclinación que me lleva a desobedecer a mi padre podría ser de parte
del Señor? Entonces comencé a considerar la extensión del poder paternal,
y hallé que no era totalmente arbitraria ni ilimitada, sino que tenía límites; a saber,
que en asuntos civiles, estaba confinada a cosas lícitas;
y que en asuntos espirituales y religiosos no tenía
un poder obligatorio sobre nuestra conciencia,
la cual siempre debe estar sujeta a nuestro Padre celestial.
Y por lo tanto, aunque se requiere que los hijos obedezcan a sus padres,
aun así se ordena con esta limitación, "`en el Señor.`"
"`Hijos, obedeced _en el Señor_ a vuestros padres, porque esto es justo.`"^
footnote:[Efesios 6:1]

Eso inclinó la balanza a favor de seguir adelante,
y por lo tanto continué. Y sin embargo,
no quedé completamente libre de algunas fluctuaciones
en mi mente debido a los asaltos del enemigo.
Por lo que,
aunque sabía que las señales externas no pertenecían
propiamente a la dispensación del evangelio,
con temor y gran humildad le rogué al Señor que por
favor condescendiera con la debilidad de Su siervo,
y me concediera una señal por la que pudiera saber con certeza
si mi camino era o no recto para con Él.

La señal que pedí fue, que si había hecho mal al venir como lo había hecho,
que fuera rechazado o recibido fríamente en el lugar al que me dirigía.
Pero si lo que me había propuesto era correcto delante de Sus ojos,
que me concediera el favor de las personas hacia las que iba,
de modo que me recibieran con gran afecto y señales de amor.
En consecuencia, cuando llegué a la casa de John Raunce, adonde había decidido ir,
porque las reuniones normalmente se hacían allí,
me recibieron con una ternura más allá de lo común, especialmente Frances Raunce,
la esposa de John Raunce, que era una mujer seria y maternal,
tenía un amor puro por la Verdad y era tierna con todos los que la buscaban con sinceridad.
Esa bienvenida,
afirmándome en la creencia de que el Señor aprobaba lo que me había propuesto,
me dio gran satisfacción y alivio a mi mente, y estaba agradecido con el Señor por ello.

Así me fue allí; pero en mi casa sucedió de otra manera con mi padre.
Él, suponiendo que había subido a mi recámara cuando me quitó el sombrero,
no preguntó por mí hasta que anocheció. Entonces,
después de sentarse junto al fuego y considerar que el clima estaba muy frío,
le dijo a mi hermana, quien se había sentado a su lado:
"`Sube a la recámara de tu hermano y dile que baje.
De lo contrario, podría quedarse ahí lamentándose hasta que le dé un resfriado.`"
"`Ay señor,`" dijo ella, "`él no está en su recámara, ni tampoco en la casa.`"
Ante lo cual mi padre se sorprendió y dijo: "`¿Dónde está entonces?`"
"`No sé dónde está, señor,`" dijo ella,
"`pero sé que cuando él vio que habías devuelto su caballo,
se puso zapatos y se fue a pie, y no lo he visto desde entonces.`"
Y añadió, "`en verdad, señor, no me sorprende que se haya ido,
considerando cómo lo trataste.`"
Eso asustó mucho a mi padre,
porque lo hizo creer que me había ido de la casa para siempre.
De hecho, un gran sentimiento de aflicción cayó sobre él,
y no pudo evitar llorar y clamar en alta voz,
de modo que toda la familia lo escuchó decir: "`¡Oh, mi hijo! ¡Nunca lo volveré a ver!
Porque él es de un espíritu tan audaz y resuelto, que seguramente se pondrá en peligro,
y probablemente sea arrojado a una cárcel u otro lugar,
donde yacerá y morirá antes de que yo pueda oír de él.`"
Luego pidiéndole a mi hermana que lo llevara a su recámara,
se acostó inmediatamente en su cama, donde permaneció inquieto y gimiendo,
lamentándose a menudo durante la mayor parte de la noche, por sí mismo y por mí.

A la mañana siguiente mi hermana envió a un siervo a contarme lo que había pasado,
uno en quién ella sabía que podía confiar,
debido al amor que tenía por mí. Y aunque ella también
mandó con él ropa de cama limpia para mi uso,
en caso de que me fuera más lejos o me quedara fuera por más tiempo,
aun así me pidió que regresara a casa tan pronto como pudiera.

El relato me dejó muy inquieto,
porque estaba muy afligido por haberle ocasionado tanta tristeza a mi padre.
Hubiera regresado esa noche después de la reunión, pero los Amigos no me lo permitieron,
porque la reunión había terminado tarde, los días eran cortos en ese entonces,
y el camino era largo y embarrialado.
Además de esto, John Raunce me dijo que tenía algo en su mente que hablar con mi padre,
y que si yo me quedaba hasta el día siguiente, él iría conmigo; quizás con la esperanza,
de que al estar mi padre bajo esa tristeza por mí, tendría su corazón más abierto.
Por lo tanto,
decidí quedarme hasta la mañana siguiente y despaché al hombre con las cosas que traía,
pidiéndole que le dijera a mi hermana que si Dios lo permitía,
regresaría a casa por la mañana;
y le ordené que no le dijera a nadie más que me había visto, o dónde había estado él.

A la mañana siguiente John Raunce y yo salimos,
y cuando llegamos a las afueras del pueblo,
acordamos que él iría delante de mí y tocaría la puerta principal,
y que yo iría un poco después de él y entraría por la puerta de atrás. Así lo hizo;
y cuando una sierva se acercó y abrió la puerta,
John le preguntó si el juez estaba en casa.
Ella le dijo que sí, y le pidió que entrara y se sentara en la sala,
y luego fue y le hizo saber a su amo que había llegado
un hombre que deseaba hablar con él. Mi padre,
suponiendo que era alguien que había llegado por negocios,
fue rápidamente a verlo en la sala.
Pero se sorprendió mucho cuando se dio cuenta de que era un Cuáquero; sin embargo,
al no saber con qué propósito había llegado, se quedó para oírlo.
Pero cuando notó que se trataba de mí, él le habló bastante áspero.

Para ese momento yo ya había entrado a la cocina por la puerta trasera,
y al escuchar a mi padre hablar tan fuertemente,
comencé a dudar de que la conversación estuviera yendo bien;
y pronto estuve seguro de que no.
Porque mi padre hartándose rápidamente de estar con un Cuáquero,
dejó a John Raunce en la sala y se fue a la cocina,
donde se sorprendió aún más al encontrarme.
Verme con mi sombrero puesto hizo que olvidara que yo era ese hijo suyo,
por quien él recientemente había estado lamentándose tanto, dándolo como perdido.
Y al sentir su dolor convirtiéndose rápidamente en ira,
no pudo contenerse y cayó sobre mí con ambas manos.
Primero me quitó con violencia mi sombrero y lo arrojó lejos, y luego,
dándome algunos golpes en mi cabeza, dijo: "`Sirrah,^
footnote:[Sirrah era una palabra de reproche o desprecio,
utilizada para dirigirse a personas viles.]
¡sube a tu recámara!`"
Yo me fui inmediatamente, y él me siguió muy de cerca,
de vez en cuando dándome un golpe en la oreja.
Y como el camino a mi recámara pasaba por la sala donde estaba John Raunce,
él (¡pobre hombre!) tuvo que presenciar la escena; sin ninguna duda se lamentó por mí,
pero no pudo hacer nada para ayudarme.

Eso de verdad fue algo inexplicable,
que mi padre un día antes expresara un dolor tan grande por mí,
temiendo que nunca me volvería a ver, y que ese día, sin embargo,
haya saltado sobre mí con semejante violencia apenas me vio,
y solo porque no me quité mi sombrero;
aunque sabía bien que yo no me lo había dejado puesto para irrespetarlo,
sino por un principio religioso.
Pero, puesto que ese honor del sombrero se había convertido en un gran ídolo,
especialmente en esos tiempos,
le plació al Señor poner a Sus siervos a testificar firmemente contra él,
sin importar cuál fuera el sufrimiento que viniera sobre ellos por hacerlo.
Y aunque algunos, que quizás hayan sido llamados a la viña del Señor en horas postreras,
después de que el calor de ese día ha pasado en gran medida,
puedan considerar que ese testimonio es algo muy pequeño como para sufrir tanto,
como ha sucedido con algunos--no solo golpizas,
sino multas y encarcelamientos largos y duros--aun así, en esos tiempos,
los que eran ejercitados fielmente en ese testimonio no
se atrevían a "`menospreciar el día de las pequeñeces;`"^
footnote:[Zacarías 4:10]
sabiendo que aquel que lo hiciera, no sería digno de dar testimonios mayores.

Ya había perdido uno de mis sombreros, y solo me quedaba uno.
Así que me puse mi segundo sombrero, pero no me duró mucho;
porque la siguiente vez que mi padre lo vio sobre mi cabeza,
me lo arrancó violentamente y lo puso con el otro, y yo no tenía idea dónde.
Por ende, me puse mi gorro de invierno,
que era todo lo que me quedaba para usar sobre mi cabeza.
Pero lo conservé por muy poco tiempo,
porque tan pronto como mi padre fue a donde yo estaba,
lo perdí también. Ahora estaba obligado a ir con la cabeza
descubierta adondequiera que tuviera que ir,
tanto dentro como fuera de la casa.
Eso sucedió en el onceavo mes, el que llamaban enero,^
footnote:[Hasta 1752,
Marzo era considerado el primer mes del año en toda Inglaterra y sus colonias.]
cuando el frío era muy penetrante; entonces, yo que había sido criado más delicadamente,
me resfrié de tal manera, que mi cara y mi cabeza se hincharon mucho,
y mis encías se llenaron de llagas tan grandes, que no podía masticar la comida,
ni tragar líquidos sin dificultad.
Esa enfermedad duró un largo tiempo, y sufrí mucho dolor sin recibir mucha compasión,
salvo de mi pobre hermana, que hizo lo que pudo para darme alivio.

Fui retenido como una especie de prisionero por el resto del invierno,
pues no tenía manera de salir a estar con los Amigos,
ni ellos tenían libertad de llegar a verme.
Por lo tanto, pasé la mayoría del tiempo en mi recámara,
esperando en el Señor y leyendo mayormente la Biblia.
Pero cada vez que tenía la ocasión de hablar con mi padre,
aunque ya no tenía sombrero para ofenderlo, mi lenguaje lo hacía igualmente.
Porque no me atrevía a tratarlo con el acostumbrado lenguaje adulador,
sino con el sencillo del tuteo según lo requiriera la ocasión,
y luego él no dudaba en golpearme con sus puños.

Recuerdo que en una de esas ocasiones, después de que él me había golpeado de esa manera,
me mandó (como normalmente hacía en esos momentos) a mi recámara.
Mientras lo hacía, me siguió hasta el pie de las escaleras y me dio un último golpe.
Entonces, en un tono muy enojado, dijo: "`¡Sirrah, si te vuelvo a oír _tutearme,_
te golpearé hasta que te tragues tus dientes!`"
Me afligió mucho oírlo hablar de esa forma;
y al sentir que una palabra se levantaba en mi corazón,
me volteé otra vez y calmadamente le dije:
"`¿No sería justo que Dios te tratara así a _ti_ cuando le hablaras
de _tú_ a Él?`" Aunque tenía levantada su mano en ese momento,
vi como descendía y decaía su semblante, y se fue y me dejó parado ahí. Yo, sin embargo,
subí a mi recámara y clamé al Señor,
pidiéndole fervientemente que le placiera abrir los ojos de mi padre,
para que pudiera ver contra quién peleaba y por qué razón, y volviera su corazón.

Después de eso tuve
un corto período de descanso y quietud de esos ataques,
en el que mi padre no me dijo nada,
ni me dio la oportunidad de decirle nada a él. Todavía estaba bajo un tipo de confinamiento,
pero me di cuenta,
de que aunque estar fuera de casa y en libertad entre
mis amigos me hubiera sido más placentero,
estar en casa en ese momento era mi lugar apropiado,
y que era como una escuela en la que tenía que aprender con paciencia a llevar la cruz,
así que me sometí voluntariamente.

Pero después de poco de tiempo,
una nueva tormenta--más feroz y fuerte que todas
las anteriores--se levantó y cayó sobre mí;
la ocasión de la cual fue la siguiente: Mi padre, habiendo sido en sus años de juventud,
especialmente cuando vivía en Londres,
un constante oyente de los que eran llamados predicadores puritanos,
y por eso había acumulado una cantidad significativa de conocimiento de las Escrituras,
a veces, aunque no constantemente ni muy seguido,
hacía que su familia se reuniera los primeros días
en la noche para exponerles un capítulo y orar.
En ese momento su familia, como también sus bienes, eran pocos,
porque mi madre y hermano habían muerto y mi hermana mayor estaba en Londres.
Y por haber abandonado la agricultura,
también había despedido a la mayoría de sus sirvientes,
de modo que solo tenía un siervo y una sirvienta.
Sucedió entonces que la noche de un primer-día, le pidió a mi hermana,
que estaba sentada con él en la sala, que les dijera a los siervos que entraran a orar.

No sé si eso fue hecho intencionalmente como una prueba para mí;
pero sin duda demostró serlo.
Porque los siervos, sintiendo mucho amor por mí,
y estando disgustados por la conducta de mi padre hacia mí, no se apresuraron a entrar,
sino que se quedaron hasta que fueron llamados por segunda vez.
Eso ofendió tanto a mi padre, que cuando finalmente entraron, en lugar de orar,
les preguntó por qué no habían llegado cuando fueron llamados la primera vez.
La respuesta que le dieron aumentó su disgusto en lugar de abatirlo, entonces él,
con un tono de enojo dijo: "`¡Llamen a ese sujeto,`" refiriéndose a mí,
que me había quedado solo en la cocina, "`porque él es la causa de todo esto!`"
Así como se habían tardado en entrar,
también se mostraron renuentes a decirme que entrara,
temiendo que el efecto del disgusto de mi padre cayera sobre mí, como sucedió pronto;
porque al oír lo que se había dicho, no esperé a que me llamaran,
sino que entré por mi propia cuenta.
Apenas entré,
mi padre descargó su disgusto sobre mí con expresiones muy duras e hirientes; lo cual,
al verlo entregado a su pasión,
me hizo decirle (en la aflicción de mi corazón) las siguientes palabras:
"`Los que puedan orar en ese espíritu, que lo hagan; pero por mi parte, yo no puedo.`"
Cuando mi padre escuchó esas palabras, se lanzó sobre mí con ambos puños; y luego,
pensando que eso no era suficiente, se apresuró al lugar donde estaba su bastón,
y tomándolo, comenzó a golpearme, creo que con todas sus fuerzas.
Como estaba con la cabeza descubierta,
sus golpes seguramente me habrían quebrado el cráneo,
si yo no hubiera puesto mi brazo sobre mi cabeza para protegerlo.

Cuando el siervo de mi padre vio lo que estaba sucediendo, no pudo contenerse,
se metió entre nosotros y agarró el bastón. Aunque no intentó quitárselo,
por la fuerza de su mano lo sostuvo tan fuertemente
que evitó que mi padre siguiera golpeándome,
lo cual solo hizo que se enfureciera más. No me gustó que se interpusiera,
y le dije que soltara el bastón y se fuera; lo hizo inmediatamente,
y al voltearse para irse y aflojar el bastón, recibió un golpe en los hombros,
que sin embargo, no le hizo mucho daño.

Pero entonces mi hermana, temiendo que mi padre volviera a golpearme,
le pidió que se detuviera; añadiendo: "`En serio señor, si lo golpeas una vez más,
abriré la ventana y gritaré '`¡asesino!`'; porque temo que vayas a matar a mi hermano.`"
Eso detuvo su mano, y después de algunas amenazas, me ordenó que me fuera a mi recámara,
lo cual hice--como siempre hacía cada vez que me lo ordenaba.
Mi hermana me siguió inmediatamente para ver mi brazo y vendar mis heridas,
porque mi brazo estaba muy herido e hinchado de la muñeca al codo,
y en algunos lugares la piel estaba rota y desgarrada.
Pero aunque mi brazo estaba muy herido, y por un tiempo me dolió mucho,
tenía paz y quietud en mi mente, estando más afligido por mi padre que por mí mismo,
porque sabía que se había herido más a sí mismo que a mí.

Esa fue, según recuerdo, la última vez que mi padre llamó a su familia a orar.
También fue la última vez que me maltrató así, por lo menos tan severamente.
Poco después de eso, mi hermana mayor,
que durante todo ese tiempo había estado en Londres, regresó a casa.
Se preocupó mucho al ver que yo era un Cuáquero,
un nombre de oprobio y gran desprecio en ese tiempo; y habiendo estado en Londres,
sin duda había oído la peor descripción de ellos.
Sin embargo, aunque ella le desagradaba ese pueblo,
su tierno afecto hacia mí le hizo sentir compasión en lugar de desprecio; y más todavía,
cuando supo el duro trato que había recibido de mi padre.

El resto del invierno lo pasé viviendo de manera retirada y solitaria,
no teniendo a nadie con quien conversar, a nadie a quien abrirle mi corazón,
a nadie a quien pedirle consejo, a nadie en quien buscar alivio,
sino únicamente el Señor; quien, sin embargo, era superior a todos.
No obstante,
pensaba que tener la compañía y sociedad de amigos
fieles y sabios habría sido muy bueno para mí,
como también de ayuda en mi viaje espiritual.
En realidad, pensaba que había progresado lentamente,
y mi alma gemía continuamente en busca de más crecimiento;
la experiencia de lo cual me hizo escribir las siguientes líneas:

[verse]
____
El árbol del invierno
Se asemeja a mí,
Cuya savia yace en su raíz.

La primavera llega;
y yo como ella
brotaré, retoñaré, lo espero así.
____

Finalmente,
le plació al Señor mover a Isaac Penington y a su esposa a visitar a mi padre,
para ver cómo me estaba yendo.
Se quedaron con nosotros toda la noche,
y conversaron mucho con mi padre sobre los principios de la Verdad en general,
y sobre mí en particular, de lo cual, yo no estaba al tanto;
pero recuerdo haber oído después lo siguiente:
Cuando mi padre y yo estuvimos en su casa unos meses antes, Mary Penington,
en una conversación entre ellos,
le había comentado cuán rudamente había tratado su suegro, el concejal Penington,
a su esposo por causa del sombrero.
Mi padre--sin tener idea de que ese sería su caso
pronto--censuró mucho al concejal Penington^
footnote:[El padre de Isaac Penington (Sir Isaac Pennington Sr.
1584-1661) fue un conocido político inglés y Puritano Congregacionalista,
que formó parte de la Cámara de los Comunes de 1640 a 1653,
y fue alcalde mayor de Londres en 1642 y 1643.
Fue miembro del tribunal que condenó y ejecutó a Carlos I por traición,
y posteriormente se convirtió en un destacado miembro del gobierno de Oliver Cromwell.
Con la Restauración de Carlos II en 1660,
Pennington padre fue juzgado por alta traición y encarcelado en la Torre de Londres,
donde murió a la espera de su ejecución el 16 de diciembre de 1661.
(Isaac Penington Jr. suprimió la "`n`" de su nombre,
quizá para no ser confundido con su padre).]
por esa conducta,
preguntándose por qué a un hombre tan sabio como él le importaría
algo tan trivial como quitarse o dejarse un sombrero,
y no se abstuvo de condenarlo abiertamente por ello.

Eso le dio una oportunidad, por así decirlo, para acorralarlo.
Y como habían mantenido una relación por mucho tiempo,
y él siempre le había tenido mucha estima y respeto; ella,
que era una mujer de gran sabiduría, de palabra fácil y de un espíritu muy determinado,
lo presionó tanto con ese argumento,
que él estaba completamente perdido sin saber cómo defenderse.

Después de la cena del día siguiente,
cuando estaban listos para tomar el coche y regresar a casa,
ella le pidió a mi padre que, debido a que mi compañía le resultaba tan desagradable,
me diera permiso para ir y pasar un tiempo con ellos, donde sin duda sería bienvenido.
Al principio estaba muy indispuesto a dejarme ir, y puso muchas objeciones en contra.
Pero todas fueron respondidas y eliminadas tan claramente por ella,
que al no hallar ninguna excusa más que alegar, finalmente dejó que yo decidiera;
y yo rápidamente incliné la balanza a favor de ir.

Habíamos llegado a un lado del coche antes de que eso se arreglara,
y cuando yo estaba listo para entrar,
una de mis hermanas le informó privadamente a mi
padre que yo no llevaba un sombrero puesto.
Eso lo alarmó un poco,
porque no le pareció apropiado que dejara la casa
y me quedara en otro lugar sin un sombrero.
Por lo tanto, le susurró a mi hermana que me buscara un sombrero,
y mientras tanto entretuvo a los Penington con algo de conversación. Pero
tan pronto vio que el sombrero se acercaba,
no se quiso quedar hasta que llegara, para evitar que me lo pusiera en su presencia.
Así que terminó su conversación abruptamente,
se despidió de ellos y se apresuró a entrar antes de que me dieran el sombrero.

Oh, que grande fue el amor y la multitud de bondades
que recibí de mis dignos amigos Isaac y Mary Penington,
mientras estuve en su familia.
Ellos en verdad fueron como padres cariñosos y tiernas nodrizas para mí,
en el tiempo de mi niñez espiritual.
Porque además de su consejo valioso y oportuno, y su conducta ejemplar,
siempre que la reunión no era en su propia casa,
me proporcionaban los medios para asistir a otras reuniones de Amigos en ese condado.
En efecto, el tiempo que pasé con ellos fue tan bien utilizado,
que no solo me dio gran satisfacción, sino que en una buena medida,
me resultó de ventaja espiritual en la Verdad.
Le plació al Señor en Su misericordia, visitarme con Su Espíritu vivificante y Su vida,
de modo que llegué a sentir la operación de Su poder en mi corazón,
echando lo que era contrario a Su voluntad, y concediéndome, en medida,
dominio sobre ello.

[.asterism]
'''

__Thomas Ellwood continuó en verdadera sumisión al Espíritu de Verdad, y por tanto,
siguió creciendo hasta convertirse en un anciano estimado
y un miembro muy útil en la antigua Sociedad de Amigos.
Joseph Wyeth, describiendo su carácter dice: "`Él era un hombre de aspecto agradable,
de una libre y generosa disposición, de temperamento cortés y afable,
y de agradable conversación; un caballero, un erudito, un Cristiano verdadero,
un escritor eminente, un buen vecino y un amigo tierno.`"
Por muchos años, Thomas Ellwood estuvo muy ocupado con su pluma defendiendo la Verdad,
publicando libros y tratados en respuesta a las diversas calumnias y tergiversaciones
que eran publicadas por los oponentes de la Sociedad.
También publicó una obra histórica muy larga, del Antiguo y Nuevo Testamento,
llamada "`Historia Sagrada;`" y un escrito poético
llamado "`Davideis,`" sobre la vida de David,
el rey de Israel.
Sin embargo,
probablemente sea más conocido por quien editó y publicó el diario de George Fox,
el cual fue impreso en 1694.
En el año 1713,
después de sufrir una apoplejía y quedarle paralizado el lado derecho de su cuerpo,
su salud comenzó a deteriorarse y dejó esta vida a los setenta
y cuatro años. Cuando estaba cerca de su final,
en presencia de algunos amigos, dijo con su corazón muy quebrantado:
"`Estoy lleno de gozo y paz.
Mi espíritu está lleno de gozo.`"__
